/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package core.components;

/**
 *
 * @author tchabole
 */
public enum Property {
    //Weapon Property
    CRITICAL_HIT_CHANCE("CHC"),
    CRITICAL_HIT_DAMAGE("CHD"),
    HEADSHOT_DAMAGE("HD"),
    WEAPON_DAMAGE("WD"),
    ACCURACY("AC"),
    STABILITY("ST"),
    OPTIMAL_RANGE("OR"),
    MAGAZINE_SIZE("MS"),
    RELOAD_SPEED("RL"),
    REDUCED_THREAT("RT"),
    INCREASED_THREAT("IT"),
    RATE_OF_FIRE("ROF"),
    OUT_OF_COVER_DAMAGE("OOCD"),
    
    //Gear Main Property
    FIREARM("FA"),
    STAMINA("ST"),
    ELECTRONIC("EL"),
    
    //Empty Mod Slot
    EMPTY("EMP"),
    
    //Gear Additional Property
    ARMOR("ARM"),
    HEALTH("HEA"),
    HEALTH_ON_KILL("HOK"),
    EXOTIC_DAMAGE_RESILIENCE("EDR"),
    SKILL_HASTE("SKH"),
    SKILL_POWER("SKP"),
    PERCENTAGE_SKILL_POWER("PSKP"),
    SIGNATURE_RESOURCE_GAIN("SRG"),
    ENEMY_ARMOR_DAMAGE("EAD"),
    DAMAGE_VS_ELITES("DVE"),
    PROTECTION_VS_ELITES("PVE"),
    SHOCK_RESISTANCE("SHR"),
    BURN_RESISTANCE("BUR"),
    DISORIENT_RESISTANCE("DOR"),
    BLIND_DEAF_RESITANCE("BDR"),
    DISRUPT_RESISTANCE("DRI"),
    BLEED_RESISTANCE("BLR"),
    SCAVENGING("SCA"),
    KILL_XP("KXP"),
    AMMO_CAPACITY("AMC"),
    LMG_DAMAGE("LMGD"),
    SMG_DAMAGE("SMGD"),
    MMR_DAMAGE("MMRD"),
    PISTOL_DAMAGE("PISD"),
    SHOTGUN_DAMAGE("SHGD"),
    ASSAULT_DAMAGE("ASRD"),
    PERCENTAGE_LMG_DAMAGE("PLMGD"),
    PERCENTAGE_SMG_DAMAGE("PSMGD"),
    PERCENTAGE_MMR_DAMAGE("PMMRD"),
    PERCENTAGE_PISTOL_DAMAGE("PPISD"),
    PERCENTAGE_SHOTGUN_DAMAGE("PSHGD"),
    PERCENTAGE_ASSAULT_DAMAGE("PASRD"),
    
    
    //Perf Mod Property
    PULSE_RANGE("PUR"),
    PULSE_DURATION("PUD"),
    PULSE_CRITICAL_HIT_CHANCE("PCHC"),
    PULSE_CRITICAL_HIT_DAMAGE("PCHD"),
    FIRST_AID_SELF_HEAL("FASH"),
    FIRST_AID_ALLY_HEAL("FAAH"),
    FIRST_AID_RADIUS("FAR"),
    FIRST_AID_DEPLOYMENT_RANGE("FADR"),
    SUPPORT_STATION_RANGE("SSR"),
    SUPPORT_STATION_HEALING_SPEED("SSHS"),
    SUPPORT_STATION_REVIVE_TIME("SSRT"),
    SUPPORT_STATION_DURATION("SSD"),
    SUPPORT_STATION_HEALTH("SSH"),
    STICKY_BOMB_DAMAGE("SBB"),
    STICKY_BOMB_EXPLOSION_RADIUS("SBER"),
    STICKY_BOMB_DEPLOYMENT_RANGE("SBDR"),
    TURRET_DAMAGE("TD"),
    TURRET_ATTACK_RANGE("TAR"),
    TURRET_DURATION("TD"),
    TURRET_HEALTH("TH"),
    SEEKER_MINE_DAMAGE("SMD"),
    SEEKER_MINE_EXPLOSION_RADIUS("SMER"),
    SEEKER_MINE_DETECTION_RANGE("SMDR"),
    SEEKER_MINE_DURATION("SMD"),
    SEEKER_MINE_HEALTH("SMH"),
    BALLISTIC_SHIELD_HEALTH("BSH"),
    BALLISTIC_SHIELD_DAMAGE("BSD"),
    BALLISTIC_SHIELD_DAMAGE_RESILIENCE("BSDR"),
    SMART_COVER_DAMAGE_RESILIENCE("SCDR"),
    SMART_COVER_WEAPON_STABILITY("SCWS"),
    SMART_COVER_WEAPON_ACCURACY("SCWA"),
    SMART_COVER_RANGE("SCR"),
    SMART_COVER_DURATION("SCD"),
    SMART_COVER_DEPLOYMENT_RANGE("SCDR"),
    MOBILE_COVER_HEALTH("MCH"),
    MOBILE_COVER_DAMAGE_RESILIENCE("MCDR"),
    MOBILE_COVER_BLAST_RESILIENCE("MCBR"),
    
    //Gear Set Bonuses
    GEAR_HEADSHOT_DAMAGE("G_HSD"),
    GEAR_OPTIMAL_RANGE("G_OPR");
    
    private String value;
    
    private Property(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return value;
    }
}
