CREATE TABLE IF NOT EXISTS `GEARSET` (
    `NAME`	TEXT NOT NULL
);

INSERT OR IGNORE INTO `GEARSET` (`rowid`,`NAME`) VALUES 
    (1, "Hunter's Faith"), (2, "Reclaimer");

CREATE TABLE IF NOT EXISTS `WEAPON_TALENT` (
    `NAME`	TEXT NOT NULL
);

INSERT OR IGNORE INTO `WEAPON_TALENT` (`rowid`,`NAME`) VALUES 
    (1, "Brutal"), (2, "Deadly"), (3, "Destructive"), (4, "Ferocious");

CREATE TABLE IF NOT EXISTS `GEAR` (
    `CLASS_TYPE`	TEXT NOT NULL,
    `GEAR_SET_ID`	INTEGER NOT NULL,
    `GEARSCORE` INTEGER NOT NULL,
    `ARMOR`	REAL NOT NULL,
    `FA`	REAL NOT NULL,
    `ST`	REAL NOT NULL,
    `EL`	REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS `GEAR_BONUSES` (
    `GEAR_ID`	INTEGER NOT NULL,
    `PROP_VALUE_ID`	INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS `MODDED_GEAR` (
    `GEAR_ID`	INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS `MODDED_GEAR_MODS` (
    `MODDED_GEAR_ID`	INTEGER NOT NULL,
    `MOD_ID`	INTEGER NOT NULL,
    `MOD_POSITION` TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS `MODS` (
    `CLASS_TYPE`	TEXT NOT NULL,
    `NAME`	TEXT NOT NULL,
    `MOD_TYPE`	TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS `MOD_BONUSES` (
    `MOD_ID`	INTEGER NOT NULL,
    `PROP_VALUE_ID`	INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS `PROP_VALUE` (
    `PROPERTY`	TEXT NOT NULL,
    `VALUE`	REAL NOT NULL,
    `POSITION`	TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS `WEAPON` (
    `TYPE`	TEXT NOT NULL,
    `GEAR_SCORE` INTEGER NOT NULL,
    `BONUS_ID`	INTEGER NULL,
    `BASE_DMG`	REAL NOT NULL,
    `MAIN_TALENT_ID`   INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS `WEAPON_EXTRA_TALENTS` (
    `WEAPON_ID`	INTEGER NOT NULL,
    `WEAPON_TALENT_ID`	INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS `MODDED_WEAPON` (
    `WEAPON_ID`	INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS `MODDED_WEAPON_MODS` (
    `MODDED_WEAPON_ID`	INTEGER NOT NULL,
    `MOD_ID`	INTEGER NOT NULL,
    `MOD_POSITION` TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS `BUILD` (
    `NAME`	TEXT NOT NULL,
    `BACKPACK_ID`	INTEGER NOT NULL,
    `BODYARMOR_ID`	INTEGER NOT NULL,
    `GLOVES_ID`   INTEGER NOT NULL,
    `HOLSTER_ID`   INTEGER NOT NULL,
    `KNEEPADS_ID`   INTEGER NOT NULL,
    `MASK_ID`   INTEGER NOT NULL,
    `WEAPON_1_ID`   INTEGER NULL,
    `WEAPON_2_ID`   INTEGER NULL
);