/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frontend.main;

/**
 *
 * @author tchabole
 */
public class BuildGUI extends javax.swing.JFrame {

    /**
     * Creates new form BuildGUI
     */
    public BuildGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topStatPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JSplitPane();
        buildsPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        defaultBuildTab = new javax.swing.JPanel();
        buildContentPanel = new javax.swing.JPanel();
        bodyArmorPanel = new javax.swing.JPanel();
        bodyArmorLabel = new javax.swing.JLabel();
        bodyArmorGears = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        backPackPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        buildSaveBtn = new javax.swing.JButton();
        buildDeleteBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        build1Tab = new javax.swing.JPanel();
        componentPanel = new javax.swing.JSplitPane();
        moddedPanel = new javax.swing.JPanel();
        moddedTopPanel = new javax.swing.JPanel();
        moddedMainPanel = new javax.swing.JPanel();
        gearFormPanel = new javax.swing.JPanel();
        mainParamsPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        bonusesPanel = new javax.swing.JPanel();
        bonus1Panel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField8 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        bonus2Panel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField9 = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        iconPanel = new javax.swing.JPanel();
        moddedBottomPanel = new javax.swing.JPanel();
        componentSaveBtn = new javax.swing.JButton();
        componentDeleteBtn = new javax.swing.JButton();
        componentnewBtn = new javax.swing.JButton();
        modsPanel = new javax.swing.JSplitPane();
        modsList = new javax.swing.JScrollPane();
        jList9 = new javax.swing.JList();
        mainModsPanel = new javax.swing.JPanel();
        attribsPanel = new javax.swing.JPanel();
        attrib1Panel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jTextField6 = new javax.swing.JTextField();
        Attrib2Panel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jTextField7 = new javax.swing.JTextField();
        bottomModsPanel = new javax.swing.JPanel();
        modSaveBtn = new javax.swing.JButton();
        modDeleteBtn = new javax.swing.JButton();
        modNewBtn = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 580));

        topStatPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Stats"));
        topStatPanel.setPreferredSize(new java.awt.Dimension(497, 50));

        javax.swing.GroupLayout topStatPanelLayout = new javax.swing.GroupLayout(topStatPanel);
        topStatPanel.setLayout(topStatPanelLayout);
        topStatPanelLayout.setHorizontalGroup(
            topStatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1066, Short.MAX_VALUE)
        );
        topStatPanelLayout.setVerticalGroup(
            topStatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        getContentPane().add(topStatPanel, java.awt.BorderLayout.NORTH);

        mainPanel.setDividerLocation(600);
        mainPanel.setMinimumSize(new java.awt.Dimension(0, 0));

        buildsPanel.setPreferredSize(new java.awt.Dimension(400, 107));
        buildsPanel.setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Builds"));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        defaultBuildTab.setLayout(new java.awt.BorderLayout());

        buildContentPanel.setPreferredSize(new java.awt.Dimension(30, 30));
        buildContentPanel.setLayout(new java.awt.GridLayout(0, 2, 10, 5));

        bodyArmorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bodyArmorPanel.setLayout(new java.awt.GridLayout(1, 2));

        bodyArmorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bodyArmorLabel.setText("BodyArmor");
        bodyArmorPanel.add(bodyArmorLabel);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        bodyArmorGears.setViewportView(jList1);

        bodyArmorPanel.add(bodyArmorGears);

        buildContentPanel.add(bodyArmorPanel);

        backPackPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        backPackPanel.setLayout(new java.awt.GridLayout(1, 2));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BackPack");
        backPackPanel.add(jLabel2);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        backPackPanel.add(jScrollPane2);

        buildContentPanel.add(backPackPanel);

        defaultBuildTab.add(buildContentPanel, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(531, 24));

        buildSaveBtn.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        buildSaveBtn.setText("Save");

        buildDeleteBtn.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        buildDeleteBtn.setText("Delete");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel1.setText("Name:");

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jTextField10.setText("jTextField10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                .addComponent(buildDeleteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buildSaveBtn)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buildSaveBtn)
                    .addComponent(buildDeleteBtn)
                    .addComponent(jLabel1)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        defaultBuildTab.add(jPanel1, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("Default", defaultBuildTab);

        javax.swing.GroupLayout build1TabLayout = new javax.swing.GroupLayout(build1Tab);
        build1Tab.setLayout(build1TabLayout);
        build1TabLayout.setHorizontalGroup(
            build1TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        build1TabLayout.setVerticalGroup(
            build1TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Build1", build1Tab);

        buildsPanel.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        mainPanel.setLeftComponent(buildsPanel);

        componentPanel.setDividerLocation(320);
        componentPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        moddedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Modded Component"));
        moddedPanel.setLayout(new java.awt.BorderLayout());

        moddedTopPanel.setPreferredSize(new java.awt.Dimension(365, 10));

        javax.swing.GroupLayout moddedTopPanelLayout = new javax.swing.GroupLayout(moddedTopPanel);
        moddedTopPanel.setLayout(moddedTopPanelLayout);
        moddedTopPanelLayout.setHorizontalGroup(
            moddedTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );
        moddedTopPanelLayout.setVerticalGroup(
            moddedTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        moddedPanel.add(moddedTopPanel, java.awt.BorderLayout.NORTH);

        moddedMainPanel.setLayout(new java.awt.BorderLayout());

        gearFormPanel.setLayout(new java.awt.BorderLayout());

        mainParamsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Main"));
        mainParamsPanel.setMinimumSize(new java.awt.Dimension(336, 60));
        mainParamsPanel.setPreferredSize(new java.awt.Dimension(265, 100));
        mainParamsPanel.setLayout(new java.awt.GridLayout(0, 6));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("GearSet/Talent:");
        mainParamsPanel.add(jLabel9);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mainParamsPanel.add(jComboBox1);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("GearScore:");
        mainParamsPanel.add(jLabel14);

        jTextField5.setText("jTextField5");
        mainParamsPanel.add(jTextField5);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Armor:");
        mainParamsPanel.add(jLabel10);

        jTextField1.setText("jTextField1");
        mainParamsPanel.add(jTextField1);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("FireArms:");
        mainParamsPanel.add(jLabel11);

        jTextField2.setText("jTextField2");
        mainParamsPanel.add(jTextField2);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Stamina:");
        mainParamsPanel.add(jLabel12);

        jTextField3.setText("jTextField3");
        mainParamsPanel.add(jTextField3);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Electronics:");
        mainParamsPanel.add(jLabel13);

        jTextField4.setText("jTextField4");
        mainParamsPanel.add(jTextField4);

        gearFormPanel.add(mainParamsPanel, java.awt.BorderLayout.NORTH);

        bonusesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Attributes"));
        bonusesPanel.setLayout(new java.awt.GridLayout(0, 1));

        bonus1Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bonus1Panel.setLayout(new java.awt.GridLayout(1, 4));

        jLabel15.setText("Major1:");
        bonus1Panel.add(jLabel15);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bonus1Panel.add(jComboBox2);

        jTextField8.setText("jTextField8");
        bonus1Panel.add(jTextField8);

        jRadioButton1.setText("Mod?");
        bonus1Panel.add(jRadioButton1);

        bonusesPanel.add(bonus1Panel);

        bonus2Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bonus2Panel.setLayout(new java.awt.GridLayout(1, 4));

        jLabel16.setFont(jLabel16.getFont());
        jLabel16.setText("Major2:");
        bonus2Panel.add(jLabel16);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bonus2Panel.add(jComboBox3);

        jTextField9.setText("jTextField9");
        bonus2Panel.add(jTextField9);

        jRadioButton2.setText("Mod?");
        bonus2Panel.add(jRadioButton2);

        bonusesPanel.add(bonus2Panel);

        gearFormPanel.add(bonusesPanel, java.awt.BorderLayout.CENTER);

        iconPanel.setPreferredSize(new java.awt.Dimension(80, 120));

        javax.swing.GroupLayout iconPanelLayout = new javax.swing.GroupLayout(iconPanel);
        iconPanel.setLayout(iconPanelLayout);
        iconPanelLayout.setHorizontalGroup(
            iconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        iconPanelLayout.setVerticalGroup(
            iconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );

        gearFormPanel.add(iconPanel, java.awt.BorderLayout.WEST);

        moddedMainPanel.add(gearFormPanel, java.awt.BorderLayout.CENTER);

        moddedPanel.add(moddedMainPanel, java.awt.BorderLayout.CENTER);

        moddedBottomPanel.setPreferredSize(new java.awt.Dimension(365, 24));

        componentSaveBtn.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        componentSaveBtn.setText("Save");

        componentDeleteBtn.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        componentDeleteBtn.setText("Delete");

        componentnewBtn.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        componentnewBtn.setText("New");

        javax.swing.GroupLayout moddedBottomPanelLayout = new javax.swing.GroupLayout(moddedBottomPanel);
        moddedBottomPanel.setLayout(moddedBottomPanelLayout);
        moddedBottomPanelLayout.setHorizontalGroup(
            moddedBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moddedBottomPanelLayout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(componentnewBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(componentDeleteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(componentSaveBtn)
                .addContainerGap())
        );
        moddedBottomPanelLayout.setVerticalGroup(
            moddedBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moddedBottomPanelLayout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addGroup(moddedBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(componentSaveBtn)
                    .addComponent(componentDeleteBtn)
                    .addComponent(componentnewBtn)))
        );

        moddedPanel.add(moddedBottomPanel, java.awt.BorderLayout.SOUTH);

        componentPanel.setTopComponent(moddedPanel);

        modsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Mods"));
        modsPanel.setDividerLocation(101);

        jList9.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        modsList.setViewportView(jList9);

        modsPanel.setLeftComponent(modsList);

        mainModsPanel.setLayout(new java.awt.BorderLayout());

        attribsPanel.setPreferredSize(new java.awt.Dimension(367, 160));
        attribsPanel.setLayout(new java.awt.GridLayout(0, 1));

        attrib1Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        attrib1Panel.setLayout(new java.awt.GridLayout(1, 3));

        jLabel17.setText("Attrb1:");
        attrib1Panel.add(jLabel17);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        attrib1Panel.add(jComboBox4);

        jTextField6.setText("jTextField6");
        attrib1Panel.add(jTextField6);

        attribsPanel.add(attrib1Panel);

        Attrib2Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Attrib2Panel.setLayout(new java.awt.GridLayout(1, 3));

        jLabel18.setText("Attrib2:");
        Attrib2Panel.add(jLabel18);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Attrib2Panel.add(jComboBox5);

        jTextField7.setText("jTextField7");
        Attrib2Panel.add(jTextField7);

        attribsPanel.add(Attrib2Panel);

        mainModsPanel.add(attribsPanel, java.awt.BorderLayout.CENTER);

        bottomModsPanel.setPreferredSize(new java.awt.Dimension(265, 24));

        modSaveBtn.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        modSaveBtn.setText("Save");
        modSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modSaveBtnActionPerformed(evt);
            }
        });

        modDeleteBtn.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        modDeleteBtn.setText("Delete");

        modNewBtn.setFont(modNewBtn.getFont().deriveFont(modNewBtn.getFont().getSize()-2f));
        modNewBtn.setText("New");

        javax.swing.GroupLayout bottomModsPanelLayout = new javax.swing.GroupLayout(bottomModsPanel);
        bottomModsPanel.setLayout(bottomModsPanelLayout);
        bottomModsPanelLayout.setHorizontalGroup(
            bottomModsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomModsPanelLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(modNewBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modDeleteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bottomModsPanelLayout.setVerticalGroup(
            bottomModsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomModsPanelLayout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addGroup(bottomModsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modNewBtn)
                    .addComponent(modDeleteBtn)
                    .addComponent(modSaveBtn)))
        );

        mainModsPanel.add(bottomModsPanel, java.awt.BorderLayout.SOUTH);

        modsPanel.setRightComponent(mainModsPanel);
        mainModsPanel.getAccessibleContext().setAccessibleName("");
        mainModsPanel.getAccessibleContext().setAccessibleParent(modsPanel);

        componentPanel.setBottomComponent(modsPanel);

        mainPanel.setRightComponent(componentPanel);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        menuBar.add(jMenu1);

        jMenu2.setText("Edit");
        menuBar.add(jMenu2);

        jMenu3.setText("Help");
        menuBar.add(jMenu3);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modSaveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modSaveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuildGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuildGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuildGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuildGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuildGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Attrib2Panel;
    private javax.swing.JPanel attrib1Panel;
    private javax.swing.JPanel attribsPanel;
    private javax.swing.JPanel backPackPanel;
    private javax.swing.JScrollPane bodyArmorGears;
    private javax.swing.JLabel bodyArmorLabel;
    private javax.swing.JPanel bodyArmorPanel;
    private javax.swing.JPanel bonus1Panel;
    private javax.swing.JPanel bonus2Panel;
    private javax.swing.JPanel bonusesPanel;
    private javax.swing.JPanel bottomModsPanel;
    private javax.swing.JPanel build1Tab;
    private javax.swing.JPanel buildContentPanel;
    private javax.swing.JButton buildDeleteBtn;
    private javax.swing.JButton buildSaveBtn;
    private javax.swing.JPanel buildsPanel;
    private javax.swing.JButton componentDeleteBtn;
    private javax.swing.JSplitPane componentPanel;
    private javax.swing.JButton componentSaveBtn;
    private javax.swing.JButton componentnewBtn;
    private javax.swing.JPanel defaultBuildTab;
    private javax.swing.JPanel gearFormPanel;
    private javax.swing.JPanel iconPanel;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel mainModsPanel;
    private javax.swing.JSplitPane mainPanel;
    private javax.swing.JPanel mainParamsPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton modDeleteBtn;
    private javax.swing.JButton modNewBtn;
    private javax.swing.JButton modSaveBtn;
    private javax.swing.JPanel moddedBottomPanel;
    private javax.swing.JPanel moddedMainPanel;
    private javax.swing.JPanel moddedPanel;
    private javax.swing.JPanel moddedTopPanel;
    private javax.swing.JScrollPane modsList;
    private javax.swing.JSplitPane modsPanel;
    private javax.swing.JPanel topStatPanel;
    // End of variables declaration//GEN-END:variables
}
