/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frontend.main;

import backend.Persistable;
import backend.dbs.SQLLite;
import core.build.*;
import core.components.*;
import core.components.gear.*;
import core.components.gearsets.*;
import core.utils.Constants;
import frontend.components.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Set;

/**
 *
 * @author tchabole
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Constants for laying out the GUI.
     */
    private final static int HEIGHT = 580,  WIDTH = 1080;
    public final static java.awt.Font DEFAULT_FONT = new java.awt.Font("Tahoma", 0, 9);
    public final static java.awt.Font DEFAULT_FONT_BOLD = new java.awt.Font("Tahoma", java.awt.Font.BOLD, 9);
    
    
    private HashMap<String,GearSet> gearSetsMap;
    private HashMap<Integer,Property[]> propertyListMap;
    private HashMap<Integer,GearSet> gearSets;
    private GearSet[] gearSetsList;

    
    private HashMap<Integer,ModdedWeapon> mainWeapons;
    private HashMap<Integer,ModdedWeapon> pistols;
    
    private HashMap<Integer,Mod> modsMap;
    private HashMap<Integer,FullBuild> fullbuilds;
            
    private Persistable backend ;
    
    
    public MainGUI() {
        loadData();
        
        initComponents();
    }

    private void loadData() {
        
        gearSetsMap = new HashMap<String,GearSet>();
        gearSetsMap.put(HunterFaith.getInstance().getName(), HunterFaith.getInstance());
        gearSetsMap.put(Reclaimer.getInstance().getName(), Reclaimer.getInstance());
        
        int gearConstants[] = {Constants.GEAR_MAJ, Constants.GEAR_SKI, Constants.WEAPON_MOD, Constants.GEAR_SET};
        
        HashMap<Integer,List<Property>> tmpPropertyListMap = new HashMap<Integer,List<Property>>();
        
        for (int i : gearConstants) {
            tmpPropertyListMap.put(i, new ArrayList<Property>());
        }
        
        int category;
        for (Property prop : Property.values()) {
            category = prop.getCategory();
            for (int i : gearConstants) {
                if ( (category & i) > 0) {
                    tmpPropertyListMap.get(i).add(prop);
                }
            }
        }
        
        propertyListMap = new HashMap<Integer,Property[]>();
        for (int i : gearConstants) {
            propertyListMap.put( i ,  tmpPropertyListMap.get(i).toArray(new Property[tmpPropertyListMap.get(i).size()]) );
        }
        
                
        backend = new SQLLite("resource/dbs/test.db");
        
        
        gearSets = backend.loadGearSets(gearSetsMap);        
        gearSetsList = gearSets.values().toArray(new GearSet[gearSets.keySet().size()]);
        

        
        modsMap = backend.loadMods();
        
        

        
        fullbuilds = backend.loadFullBuilds(gearSets);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")               
    private void initComponents() {

        topStatPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JSplitPane();
        buildsPanel = new javax.swing.JPanel();
        jTabbedPanel = new javax.swing.JTabbedPane();
        defaultBuildTab = new FullBuildGUI(this, new FullBuild());
        
        componentPanel = new javax.swing.JSplitPane();
        moddedPanel = new javax.swing.JPanel();
        moddedTopPanel = new javax.swing.JPanel();
        moddedMainPanel = new javax.swing.JPanel();
        gearFormPanel = new GearFormGUI(this);

        moddedBottomPanel = new javax.swing.JPanel();
        componentSaveBtn = new javax.swing.JButton();
        componentDeleteBtn = new javax.swing.JButton();
        componentnewBtn = new javax.swing.JButton();
        modsPanel = new javax.swing.JSplitPane();
        modsScrollPane = new javax.swing.JScrollPane();
        modsList = new ModList();
        mainModsPanel = new javax.swing.JPanel();
        modFormPanel = new ModFormGUI(this);
        
        bottomModsPanel = new javax.swing.JPanel();
        modSaveBtn = new javax.swing.JButton();
        modDeleteBtn = new javax.swing.JButton();
        modNewBtn = new javax.swing.JButton();
        
        
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(WIDTH, HEIGHT));

        topStatPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Stats"));
        topStatPanel.setPreferredSize(new java.awt.Dimension(WIDTH, 80));

        
        getContentPane().add(topStatPanel, java.awt.BorderLayout.NORTH);

        mainPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        //buildsPanel.setPreferredSize(new java.awt.Dimension(400, 107));
        buildsPanel.setLayout(new java.awt.BorderLayout());

        jTabbedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Builds"));
        jTabbedPanel.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jTabbedPanel.addTab("Default", defaultBuildTab);

        FullBuild fullBuild;
        for (Integer i : fullbuilds.keySet()) {
            fullBuild = fullbuilds.get(i);
            buildTab = new FullBuildGUI(this,fullBuild);
            jTabbedPanel.addTab(fullBuild.getName(), buildTab);
        }

        buildsPanel.add(jTabbedPanel, java.awt.BorderLayout.CENTER);

        mainPanel.setLeftComponent(buildsPanel);

        
        componentPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        moddedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Modded Component"));
        moddedPanel.setLayout(new java.awt.BorderLayout());

        moddedTopPanel.setPreferredSize(new java.awt.Dimension(WIDTH, 20));


        moddedPanel.add(moddedTopPanel, java.awt.BorderLayout.NORTH);

        moddedMainPanel.setLayout(new java.awt.BorderLayout());

        moddedMainPanel.add(gearFormPanel, java.awt.BorderLayout.CENTER);

        moddedPanel.add(moddedMainPanel, java.awt.BorderLayout.CENTER);

        moddedBottomPanel.setPreferredSize(new java.awt.Dimension(365, 24));

        componentSaveBtn.setFont(DEFAULT_FONT); // NOI18N
        componentSaveBtn.setText("Save");

        componentDeleteBtn.setFont(DEFAULT_FONT); // NOI18N
        componentDeleteBtn.setText("Delete");

        componentnewBtn.setFont(DEFAULT_FONT); // NOI18N
        componentnewBtn.setText("New");

        javax.swing.GroupLayout moddedBottomPanelLayout = new javax.swing.GroupLayout(moddedBottomPanel);
        moddedBottomPanel.setLayout(moddedBottomPanelLayout);
        moddedBottomPanelLayout.setHorizontalGroup(
            moddedBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moddedBottomPanelLayout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(componentnewBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(componentDeleteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(componentSaveBtn)
                .addContainerGap())
        );
        moddedBottomPanelLayout.setVerticalGroup(
            moddedBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moddedBottomPanelLayout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addGroup(moddedBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(componentSaveBtn)
                    .addComponent(componentDeleteBtn)
                    .addComponent(componentnewBtn)))
        );

        moddedPanel.add(moddedBottomPanel, java.awt.BorderLayout.SOUTH);

        componentPanel.setTopComponent(moddedPanel);

        
        modsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Mods"));
        
        modsList.setFont(DEFAULT_FONT);

        modsScrollPane.setViewportView(modsList);

        modsPanel.setLeftComponent(modsScrollPane);

        
        mainModsPanel.setLayout(new java.awt.BorderLayout());

        


        mainModsPanel.add(modFormPanel, java.awt.BorderLayout.CENTER);

        bottomModsPanel.setPreferredSize(new java.awt.Dimension(265, 24));

        
        modSaveBtn.setFont(DEFAULT_FONT); // NOI18N
        modSaveBtn.setText("Save");
        modSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modSaveBtnActionPerformed(evt);
            }
        });

        modDeleteBtn.setFont(DEFAULT_FONT); // NOI18N
        modDeleteBtn.setText("Delete");

        modNewBtn.setFont(DEFAULT_FONT);
        modNewBtn.setText("New");

        javax.swing.GroupLayout bottomModsPanelLayout = new javax.swing.GroupLayout(bottomModsPanel);
        bottomModsPanel.setLayout(bottomModsPanelLayout);
        bottomModsPanelLayout.setHorizontalGroup(
            bottomModsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomModsPanelLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(modNewBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modDeleteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modSaveBtn)
                .addContainerGap())
        );
        bottomModsPanelLayout.setVerticalGroup(
            bottomModsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomModsPanelLayout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addGroup(bottomModsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modNewBtn)
                    .addComponent(modDeleteBtn)
                    .addComponent(modSaveBtn)))
        );

        mainModsPanel.add(bottomModsPanel, java.awt.BorderLayout.SOUTH);

        modsPanel.setRightComponent(mainModsPanel);
        

        componentPanel.setBottomComponent(modsPanel);

        mainPanel.setRightComponent(componentPanel);


        createMenu();

        pack();
        
        mainPanel.setDividerLocation( (double)0.6); 
        componentPanel.setDividerLocation( (double) 0.68 );
        modsPanel.setDividerLocation( (double) 0.5);
    }               

    private void createMenu() {
        
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        
        jMenu1.setText("File");
        menuBar.add(jMenu1);

        jMenu2.setText("Edit");
        menuBar.add(jMenu2);

        jMenu3.setText("Help");
        menuBar.add(jMenu3);

        setJMenuBar(menuBar);
    }
    
    private void modSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuildGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuildGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuildGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuildGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    
    public List<ModdedGear> getModdedGears(String gearType) {
        List<ModdedGear> moddedGearsList = new ArrayList<ModdedGear>();
        HashMap<Integer,ModdedGear>  moddedGearsMap = backend.loadModdedGears(gearSets, gearType);
        
        for (Integer i : moddedGearsMap.keySet() ) {
            moddedGearsList.add(moddedGearsMap.get(i));
        }
        
        return moddedGearsList;
    }
    
    public List<Mod> getMods(String modType) {
        List<Mod> mods = new ArrayList<Mod>();
        HashMap<Integer,Mod>  modsMap = backend.loadMods(); // TODO: modtype??
        
        for (Integer i : modsMap.keySet() ) {
            mods.add(modsMap.get(i));
        }
        
        return mods;
    }
    
    
    public GearSet[] getGearSetsList() {
        return gearSetsList;
    }
    
    public GearFormGUI getGearFormPanel() {
        return this.gearFormPanel;
    }
    
    public ModFormGUI getModFormPanel() {
        return this.modFormPanel;
    }
    
    public Property[] getPropertyList(int category) {
        return propertyListMap.get(category);
    }
    
    
    class ModList extends javax.swing.JList {
        
        ModList() {
            
            setModel(new javax.swing.AbstractListModel() {
                List<Mod> theMods =  getMods(null);
                @Override
                public int getSize() { return theMods.size(); }
                @Override
                public Mod getElementAt(int i) { return theMods.get(i); }
            });
            
            addMouseListener(new MouseAdapter() {

                @Override
                public void mousePressed(MouseEvent e) {
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    javax.swing.JList theList = (javax.swing.JList) e.getSource();
                    int index = theList.locationToIndex(e.getPoint());
                    
                    if (index >= 0) {
                        Mod theMod = (Mod) theList.getModel().getElementAt(index);
                        //getGearFormPanel().updateModdedGear(Mod, gearType);
                    }
                }
            });
        }
    }
    
    
    // Variables declaration - do not modify                     
    private ModFormGUI modFormPanel;
    private javax.swing.JPanel bottomModsPanel;
    
    
    private javax.swing.JPanel buildsPanel;
    private javax.swing.JButton componentDeleteBtn;
    private javax.swing.JSplitPane componentPanel;
    private javax.swing.JButton componentSaveBtn;
    private javax.swing.JButton componentnewBtn;
    
    
    
    
    private ModList modsList;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    
    
    
    private javax.swing.JTabbedPane jTabbedPanel;
    
    private javax.swing.JPanel mainModsPanel;
    private javax.swing.JSplitPane mainPanel;
    
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton modDeleteBtn;
    private javax.swing.JButton modNewBtn;
    private javax.swing.JButton modSaveBtn;
    private javax.swing.JPanel moddedBottomPanel;
    private javax.swing.JPanel moddedMainPanel;
    private javax.swing.JPanel moddedPanel;
    private javax.swing.JPanel moddedTopPanel;
    private javax.swing.JScrollPane modsScrollPane;
    private javax.swing.JSplitPane modsPanel;
    private javax.swing.JPanel topStatPanel;
    
    private FullBuildGUI defaultBuildTab;
    private FullBuildGUI buildTab;
    
    private GearFormGUI gearFormPanel;
    

    
    // End of variables declaration                   
}
